### ISSUE TITLE
Its work?

### ISSUE THREAD

**Issue by sendrou** [Nazar1ky/auto-twitch-drops#1]
hi, this program working?:

**Comment by Nazar1ky** [comment]
Hi, yes, but it’s in very early stages, and sometimes appear issues.

**Comment by sendrou** [comment]
![image](https://github.com/Nazar1ky/auto-twitch-drops/assets/55048208/de618e41-89ad-48ea-8671-a91c67ef2927)

**Comment by Nazar1ky** [comment]
oh, thanks for report, currently it's still in develop, try to use TwitchDropsMiner fork.

**Comment by Nazar1ky** [comment]
Btw, try to update your Python to 312. Because `fromisoformat` updated in 311 Python version. https://docs.python.org/3/library/datetime.html#datetime.date.fromisoformat

**Comment by Nazar1ky** [comment]
I'm still debugging the program, and refactoring.

**Comment by sendrou** [comment]
how i can select game for farm?

**Comment by Nazar1ky** [comment]
```
miner = TwitchMiner(twitch_login, api, game="Rust") # Put there game in str game="Rust"
await miner.run()
```

**Comment by sendrou** [comment]
Thanks

**Comment by sendrou** [comment]
Does the application not work using previously generated tokens?

**Comment by Nazar1ky** [comment]
which previously generated?

**Comment by Nazar1ky** [comment]
application saves token in cookies.json and uses it

**Comment by sendrou** [comment]
I wanted to use just cookies, but for some reason in this case it gives an error

**Comment by Nazar1ky** [comment]
can you show error here, and example of cookies

**Comment by sendrou** [comment]
I'm just changing the same data in the cookies that your program generates
<details>
<summary>Error</summary>

 Traceback (most recent call last):
  File "D:\farm rust\auto-twitch-drops-main — копия — копия\main.py", line 55, in <module>
    asyncio.run(main())
  File "C:\Users\Maksim\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Maksim\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Maksim\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\farm rust\auto-twitch-drops-main — копия — копия\main.py", line 52, in main
    await miner.run()
  File "D:\farm rust\auto-twitch-drops-main — копия — копия\autoTwitchDrops\miner.py", line 75, in run
    streamer = await self.pick_streamer()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\farm rust\auto-twitch-drops-main — копия — копия\autoTwitchDrops\miner.py", line 118, in pick_streamer
    await self.update_campaigns()
  File "D:\farm rust\auto-twitch-drops-main — копия — копия\autoTwitchDrops\miner.py", line 177, in update_campaigns
    response = await self.api.get_full_campaigns_data(campaigns_ids)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\farm rust\auto-twitch-drops-main — копия — копия\autoTwitchDrops\twitch.py", line 168, in get_full_campaigns_data
    campaigns.extend(await self.send_requests(request))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\farm rust\auto-twitch-drops-main — копия — копия\autoTwitchDrops\twitch.py", line 33, in send_requests
    raise RuntimeError(f"Error in request {request}\nResponse: {data}")
RuntimeError: Error in request [{'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': '8b30edde-281b-11ef-817c-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': 'e3e12fd0-27b6-11ef-9258-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': 'cd2758b2-25e1-11ef-9ad3-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': '4b6b6d7c-24e2-11ef-a676-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': '98c3bb44-12a0-11ef-badc-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': '57efd63b-24cf-11ef-a676-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': '5e7c5117-2818-11ef-a116-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': 'd62dfc1c-2813-11ef-a8fc-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': '730cba24-24d2-11ef-ab01-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': '33b1b01e-25e2-11ef-9008-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': '50bcfab4-1e4a-11ef-853c-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': '4f302a2c-23f0-11ef-9f07-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': 'd619ec01-229e-11ef-9ed6-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': 'fd1a2b5a-1489-11ef-a062-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': '6ef3a36f-1489-11ef-a52a-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': 'f3b02398-1488-11ef-a844-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': '7e32126c-271b-11ef-b526-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': '7b7a89ab-1385-11ef-b919-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': '857b826d-1809-11ef-9bc2-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': 'e4c908ac-1380-11ef-ab88-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': 'afc38eb9-227f-11ef-9a91-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': 'af52d24d-19b5-11ef-b378-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': 'b151857c-202b-11ef-b133-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': 'e640c56f-247c-11ef-8211-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': 'b6de1714-1c75-11ef-a889-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': '705b5da3-284d-11ef-a116-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': 'f1e31bb0-2735-11ef-8df3-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': 'cc0b1aaf-2188-11ef-b72b-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': '5bafd12c-258e-11ef-a2d1-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': 'b103225a-258b-11ef-a577-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': 'f90995d5-258b-11ef-a577-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': '0e18d68c-258d-11ef-b944-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': '4e90a26f-258d-11ef-a577-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': 'c93f689f-258c-11ef-9b06-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}, {'operationName': 'DropCampaignDetails', 'variables': {'channelLogin': '999716915', 'dropID': '57f7ff35-258c-11ef-8d8f-0a58a9feac02'}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}}]
Response: [{'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}, {'errors': [{'message': 'failed integrity check', 'path': ['user', 'dropCampaign']}], 'data': {'user': {'id': '999716915', 'dropCampaign': None, '__typename': 'User'}}, 'extensions': {'challenge': {'type': 'integrity'}, 'durationMilliseconds': 21, 'operationName': 'DropCampaignDetails', 'requestID': '01J06SFCWRQEF562Z7WFWNEKQE'}}]

</details>

**Comment by Nazar1ky** [comment]
~~Hm, that's weird issue. Did you changed user_id?~~. program automatically update data when validating. let me investigate.

**Comment by sendrou** [comment]
Yes, but the program changes it itself

**Comment by Nazar1ky** [comment]
Investigating.

**Comment by Nazar1ky** [comment]
When you auth via program, it show error?

**Comment by sendrou** [comment]
if I make a token through the program, then everything works fine

**Comment by Nazar1ky** [comment]
where you getting token?

**Comment by sendrou** [comment]
I bought accounts immediately with the created token

**Comment by Nazar1ky** [comment]
how token look? show me via XXXXXX format

**Comment by sendrou** [comment]
like this 
ug1gsmlif8lj8mb5orjn6ad93kk9my

**Comment by Nazar1ky** [comment]
Hm, it's same, can you ask how it's generated?

**Comment by Nazar1ky** [comment]
Wait, I understand, give me a minute.

**Comment by Nazar1ky** [comment]
To make that work you need add in headers Client-Id, X-Device-Id and Client-Integrity.

**Comment by sendrou** [comment]
In Json?

**Comment by Nazar1ky** [comment]
wait

**Comment by Nazar1ky** [comment]
I can't fix this but you can try and experiment with code. please use original cookies

**Comment by sendrou** [comment]
Ok, thanks for help

**Comment by Nazar1ky** [comment]
You can yourself investigate how to generate these headers, and tell me
